# Generated by Django 4.2 on 2026-09-23 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('intervalo', models.IntegerField(default=1, help_text='A cada quantos dias/semanas/meses?')),
            ],
            options={
                'verbose_name_plural': 'Recorrências',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('responsavel', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('recorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salas.recorrencia')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='salas.sala')),
            ],
            options={
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='salas.sala')),
            ],
        ),
    ]
